spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres


  liquibase:
    change-log: db/changelog/main-changelog.xml

